# Generated by Django 3.2.12 on 2022-03-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='a',
            field=models.ManyToManyField(related_name='c', to='db_app.A'),
        ),
    ]
